services:
  nginx:
    container_name: ${NGINX_CONTAINER_NAME:-template-nginx}
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx_target.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - my-central-proxy-network
    # restart: unless-stopped
    restart: always

  certbot:
    container_name: ${CERTBOT_CONTAINER_NAME:-template-certbot}
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - my-central-proxy-network

networks:
  my-central-proxy-network:
    external: true